### PR TITLE
Two small changes (README and package update match)

### PR DESCRIPTION
**Pull request by gnanet**
This small PR contains some minor fixes, and styling to README.md and the extra match on architecture of updated packages, which we discussed recently.

The next PR is going to remove some code related to "apt-get dist-upgrade" which i moved to a separate plugin that i want to publish later too

### CODE REVIEW

**Comment by gnanet** [comment]
@mitchellurgero did you overlook this, or there is some other things cooking in the kitchen? :) I am trying to push changes in smaller PR-s to achieve the state where i can start publish the first plugin: **package dist-upgrade** with package changelog display, downloading of upgrade-able packages in advance (required to get the changelog)

But prior this, i want to clean all traces of that code and functions we previously committed into the core

**Comment by mitchellurgero** [comment]
Sorry! I actually forgot about this 🥉 

Am I merging this or?

**Comment by gnanet** [comment]
@mitchellurgero yes i would like to ask you to merge this first.

**Comment by mitchellurgero** [comment]
Done and done. :)

**Pull request merged**
